src/main/java/com/example/jsfdemo/domain/Anime.java
package com.example.jsfdemo.domain;

import java.util.Date;

import javax.validation.constraints.Min;
import javax.validation.constraints.Past;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

public class Anime {
	
	private String title = "Title";
	private String genre = "Genre";
	private int year;
	private String episodes = "Episodes";
	private String studio = "Studio";
	
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getGenre() {
		return genre;
	}
	public void setGenre(String genre) {
		this.genre = genre;
	}
	public int getYear(){
		return year;
	}
	public void setYear(int year) {
        this.year = year;
	}
	public String getEpisodes() {
		return episodes;
	}
	public void setEpisodes(String episodes) {
		this.episodes = episodes;
	}
	
	public String getStudio() {
		return studio;
	}
	public void setStudio(String studio) {
		this.studio = studio;
	}
}

src/main/java/com/example/jsfdemo/web/AnimeFormBean.java
package com.example.jsfdemo.web;

import java.io.Serializable;
import java.util.Calendar;
import java.util.Date;

import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.component.UIForm;
import javax.faces.component.UIInput;
import javax.faces.context.FacesContext;
import javax.faces.event.ComponentSystemEvent;
import javax.faces.model.ListDataModel;
import javax.faces.validator.ValidatorException;
import javax.inject.Inject;
import javax.inject.Named;

import com.example.jsfdemo.domain.Anime;
import com.example.jsfdemo.service.AnimeManager;

@SessionScoped
@Named("animeBean")
public class AnimeFormBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Anime anime = new Anime();

	private ListDataModel<Anime> animes = new ListDataModel<Anime>();

	@Inject
	private AnimeManager an;

	public Anime getAnime() {
		return anime;
	}

	public void setAnime(Anime anime) {
		this.anime = anime;
	}

	public ListDataModel<Anime> getAllAnimes() {
		animes.setWrappedData(an.getAllAnimes());
		return animes;
	}

	
	public String addAnime() {
		an.addAnime(anime);
		return "showAnimes";
		
	}

	public String deleteAnime() {
		Anime animeToDelete = animes.getRowData();
		an.deleteAnime(animeToDelete);
		return null;
	}

}

src/main/webapp/add.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	<ui:define name="content">
		<h:form id="animeForm">
			<h:panelGrid columns="2">

				<h:outputText value="Add Anime with very simple form" />
				<h:commandLink action="addSimple?faces-redirect=true">
					<h:outputText value=" Add anime " />
				</h:commandLink>

				<h:outputText value="Add Anime with some validators" />
				<h:commandLink action="addValidation?faces-redirect=true">
					<h:outputText value=" Add anime " />
				</h:commandLink>

				<h:outputText value="Add Anime with JSF 2.0 ajax support" />
				<h:commandLink action="addAjax?faces-redirect=true">
					<h:outputText value=" Add anime " />
				</h:commandLink>

				<h:outputText value="Add Anime with RichFaces support" />
				<h:commandLink action="addRF?faces-redirect=true">
					<h:outputText value=" Add anime " />
				</h:commandLink>

			</h:panelGrid>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/addAjax.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	<ui:define name="content">

		<h:form id="animeform">
			<h:panelGrid columns="2">

				<h:outputText value="#{msg.animeTitleLabel}" />
				<h:inputText id="Title" value="#{animeBean.anime.Title}"
					required="#{true}" />

				<h:outputText value="#{msg.animeEPLabel}" />
				<h:inputText id="episodes" value="#{animeBean.anime.episodes}"
					validator="#{animeBean.uniquePin}" required="#{true}">
					<f:validator validatorId="pinValidator" />
					<f:ajax execute="@this" render="messages beanState" />
				</h:inputText>

				<h:outputText value="#{msg.animeGenreLabel}" />
				<h:inputText id="genre" value="#{animeBean.anime.Genre}">
				</h:inputText>

				<h:outputText value="#{msg.animeYearLabel}" />
				<h:inputText id="zipCode" value="#{animeBean.anime.Year}" />

				<h:outputText value="#{msg.animeStudioLabel}" />
				<h:inputText id="weight" value="#{animeBean.anime.Studio}">
				</h:inputText>

			</h:panelGrid>

			<h:commandButton value="#{msg.animeFormOKButton}"
				action="#{animeBean.addAnime}" />


			<h:panelGrid>
				<h:messages id="messages" showDetail="#{true}"
					showSummary="#{false}" />
			</h:panelGrid>

			<h:panelGrid id="beanState" columns="2">
				<h:outputText value="#{msg.animeTitleLabel}" />
				<h:outputText id="titleOutput" value="#{animeBean.anime.Title}" />

				<h:outputText value="#{msg.animeEpLabel}" />
				<h:outputText id="episodesOutput" value="#{animeBean.anime.episodes}" />

				<h:outputText value="#{msg.animeGenreLabel}" />
				<h:outputText id="genreOutput"
					value="#{animeBean.anime.Genre}" />
			</h:panelGrid>

		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/addRF.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">

	<ui:define name="content">
		<h:form id="animeform">
			<h:panelGrid columns="2">
			
				<h:outputText value="#{msg.animeTitleLabel}" />
				<h:inputText id="name" value="#{animeBean.anime.Title}">
					<a4j:ajax render="messages" execute="@this" />
				</h:inputText>

				<h:outputText value="#{msg.animeEpLabel}" />
				<h:inputText id="pin" value="#{animeBean.anime.episodes}" />


				<h:outputText value="#{msg.animeGenreLabel}" />
				<rich:calendar value="#{animeBean.anime.Genre}"
					id="genre" showApplyButton="#{true}">
					<a4j:ajax render="messages" execute="@this" />
				</rich:calendar>
			</h:panelGrid>

			<h:panelGrid>
				<h:messages for="" />
				<h:messages id="messages" showDetail="#{true}"
					showSummary="#{false}" />
			</h:panelGrid>

			<a4j:outputPanel ajaxRendered="true">
				<h:panelGrid columns="2">

					<h:outputText value="#{msg.animeTitleLabel}" />
					<h:outputText id="titleOutput"
						value="#{animeBean.anime.Title}" />

					<h:outputText value="#{msg.animeEpLabel}" />
					<h:outputText id="episodesOutput" value="#{animeBean.anime.episodes}" />


					<h:outputText value="#{msg.animeGenreLabel}" />
					<h:outputText id="genreOutput"
						value="#{animeBean.anime.Genre}" />

				</h:panelGrid>
			</a4j:outputPanel>
		</h:form>

	</ui:define>
</ui:composition>

src/main/webapp/addSimple.xhtml
l<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	<ui:define name="content">
		<h:form id="animeform">
			<h:panelGrid columns="2">

				<h:outputText value="#{msg.animeTitleLabel}" />
				<h:inputText id="name" value="#{animenBean.anime.Title}" />

				<h:outputText value="#{msg.animeEpLabel}" />
				<h:inputText id="yob" value="#{animeBean.anime.episodes}" />
			</h:panelGrid>

			<h:commandButton value="#{msg.animeFormOKButton}"
				action="#{animeBean.addAnime}" />
				
			<h:panelGrid>
				<h:messages showDetail="#{true}" showSummary="#{false}" />
			</h:panelGrid>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/addValidation.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	<ui:define name="content">

		<h:form id="animeForm">
            <f:event type="postValidate" listener="#{animeBean.validatePinDob}" />
            
			<h:panelGrid columns="2">

				<h:outputText value="#{msg.animeTitleLabel}" />
				<h:inputText id="Title" value="#{animeBean.anime.Title}" required="#{true}"/>

				<h:outputText value="#{msg.animeEpLabel}" />
				<h:inputText id="episodes" value="#{animeBean.anime.episodes}"
					validator="#{animeBean.uniqueEp}" required="#{true}">
					<f:validator validatorId="pinValidator" />
				</h:inputText>

				<h:outputText value="#{msg.animeGenreLabel}" />
				<h:inputText id="genre" value="#{animeBean.anime.Genre}">
				</h:inputText>

				<h:outputText value="#{msg.animeYearLabel}" />
				<h:inputText id="year" value="#{animeBean.anime.Year}" />

				<h:outputText value="#{msg.animeYearLabel}" />
				<h:inputText id="year" value="#{animeBean.anime.year}">
				</h:inputText>
			</h:panelGrid>
			
			<h:commandButton value="#{msg.animeFormOKButton}"
				action="#{animeBean.addAnime}" />


			<h:panelGrid>
				<h:messages id="messages" showDetail="#{true}"
					showSummary="#{false}" />
			</h:panelGrid>
		</h:form>

	</ui:define>
</ui:composition>

src/main/webapp/home.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	<ui:define name="content">
		<p>#{msg.applicationInfo}</p>
	</ui:define>
</ui:composition>

src/main/webapp/index.jsp
<% response.sendRedirect("home.jsf"); %>

src/main/webapp/showAnimes.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	
	<ui:define name="content">
	
    <h:form>
    
     <h:dataTable value="#{animeBean.allAnimes}" var="item">
      <f:facet name="header">#{msg.animeAllLabel}</f:facet>
      
      <h:column>
        <f:facet name="header">#{msg.animeTitleLabel}</f:facet>
        #{item.firstName}
      </h:column>
      
      <h:column>
        <f:facet name="header">#{msg.animeEPLabel}</f:facet>
        #{item.pin}
      </h:column>
      
      <h:column>
        <f:facet name="header">#{msg.action}</f:facet>
        <h:commandLink value="#{msg.actionDelete}" action="#{animeBean.deleteAnime}"/>
      </h:column>
      
     </h:dataTable>
    </h:form>
      
	</ui:define>
	
</ui:composition>

src/main/webapp/templates/default.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><ui:insert name="windowTitle">#{msg.mainWindowTitle}</ui:insert>
	</title>
</h:head>
<h:body>
  <h:outputStylesheet library="css" name="default.css" target="body" />
	<div class="heading">
	  <ui:insert name="heading">
       #{msg.mainHeading}
     </ui:insert>
    </div>
	<div class="menuAndContent">
	 <div class="menu">
	   <ui:insert name="menu">
         <ui:include src="/views/main/menu.xhtml" />
       </ui:insert>
      </div>
	  <div class="content">
	     <ui:insert name="content" />
       </div>
	</div>
</h:body>
</html>

src/main/webapp/views/main/menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
  <div>
	<h:form>
	  <ul>
		<li>
		  <h:commandLink action="home?faces-redirect=true">
			<h:outputText value="#{msg.linkHome}" />
		  </h:commandLink>
		</li>
		<li>
		  <h:commandLink action="add?faces-redirect=true">
			<h:outputText value="#{msg.animeAddLabel}" />
		  </h:commandLink></li>
		<li>
		  <h:commandLink action="showPersons?faces-redirect=true">
			 <h:outputText value="#{msg.animeAllLabel}" />
		  </h:commandLink>
		</li>
	</ul>
   </h:form>
  </div>
</ui:composition>